services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: SECRET_KEY
        generateValue: true